<?php

return [
    'domain' => env('OPENPDF_DOMAIN', 'openpdf.com.tr'),
    'organization' => env('OPENPDF_ORGANIZATION', 'OpenPDF Association'),
    'free_forever' => (bool) env('OPENPDF_FREE_FOREVER', true),
    'runtime_dir' => env('OPENPDF_RUNTIME_DIR', storage_path('app/private/runtime')),

    'visitor_limits' => [
        'max_files' => (int) env('OPENPDF_VISITOR_MAX_FILES', 100),
        'max_bytes' => (int) env('OPENPDF_VISITOR_MAX_MB', 100) * 1024 * 1024,
    ],

    'binaries' => [
        'gs' => env('OPENPDF_BINARY_GS', 'gs'),
        'libreoffice' => env('OPENPDF_BINARY_LIBREOFFICE', 'libreoffice'),
        'soffice' => env('OPENPDF_BINARY_SOFFICE', 'soffice'),
        'pdfunite' => env('OPENPDF_BINARY_PDFUNITE', 'pdfunite'),
        'pdftoppm' => env('OPENPDF_BINARY_PDFTOPPM', 'pdftoppm'),
        'pdftotext' => env('OPENPDF_BINARY_PDFTOTEXT', 'pdftotext'),
        'magick' => env('OPENPDF_BINARY_MAGICK', 'magick'),
        'img2pdf' => env('OPENPDF_BINARY_IMG2PDF', 'img2pdf'),
        'convert' => env('OPENPDF_BINARY_CONVERT', 'convert'),
    ],

    'donations' => [
        [
            'key' => 'github',
            'label' => 'GitHub Sponsors',
            'icon' => 'bi bi-github',
            'url' => env('OPENPDF_DONATE_GITHUB', 'https://github.com/sponsors/fatihalp'),
        ],
        [
            'key' => 'patreon',
            'label' => 'Patreon',
            'icon' => 'bi bi-heart-fill',
            'url' => env('OPENPDF_DONATE_PATREON', 'https://www.patreon.com/openpdf'),
        ],
        [
            'key' => 'buymeacoffee',
            'label' => 'Buy Me a Coffee',
            'icon' => 'bi bi-cup-hot-fill',
            'url' => env('OPENPDF_DONATE_BMAC', 'https://buymeacoffee.com/openpdf'),
        ],
    ],

    'locales' => [
        'en',
        'zh',
        'hi',
        'es',
        'fr',
        'ar',
        'bn',
        'pt',
        'ru',
        'ur',
        'id',
        'de',
        'ja',
        'sw',
        'mr',
        'te',
        'tr',
        'ta',
        'vi',
        'ko',
    ],

    'route_slugs' => [
        'free_converter' => [
            'en' => 'free-converter',
            'zh' => 'mianfei-zhuanhuanqi',
            'hi' => 'muft-converter',
            'es' => 'convertidor-gratis',
            'fr' => 'convertisseur-gratuit',
            'ar' => 'muhawwil-majani',
            'bn' => 'binamulye-converter',
            'pt' => 'conversor-gratis',
            'ru' => 'besplatnyy-konverter',
            'ur' => 'muft-tabdeel-karne-wala',
            'id' => 'konverter-gratis',
            'de' => 'kostenloser-konverter',
            'ja' => 'muryo-henkan',
            'sw' => 'kibadilishaji-bure',
            'mr' => 'vinamulya-converter',
            'te' => 'uchita-marpu',
            'tr' => 'ucretsiz-cevirici',
            'ta' => 'ilavasa-maatri',
            'vi' => 'trinh-chuyen-doi-mien-phi',
            'ko' => 'muryo-byeonhwan-gi',
        ],
        'site_map' => [
            'en' => 'site-map',
            'zh' => 'wangzhan-ditu',
            'hi' => 'site-manachitra',
            'es' => 'mapa-del-sitio',
            'fr' => 'plan-du-site',
            'ar' => 'khareetat-almawqie',
            'bn' => 'sait-manachitra',
            'pt' => 'mapa-do-site',
            'ru' => 'karta-sayta',
            'ur' => 'site-naksha',
            'id' => 'peta-situs',
            'de' => 'sitemap',
            'ja' => 'saito-mappu',
            'sw' => 'ramani-ya-tovuti',
            'mr' => 'sait-nakasha',
            'te' => 'site-pata',
            'tr' => 'site-haritasi',
            'ta' => 'thal-varai-padam',
            'vi' => 'so-do-trang',
            'ko' => 'saiteu-maep',
        ],
    ],

    'tools' => [
        'pdf_to_word' => [
            'mode' => 'backend',
            'accept_extensions' => ['pdf'],
            'accept_mime' => ['application/pdf'],
        ],
        'pdf_to_excel' => [
            'mode' => 'backend',
            'accept_extensions' => ['pdf'],
            'accept_mime' => ['application/pdf'],
        ],
        'pdf_to_jpg' => [
            'mode' => 'backend',
            'accept_extensions' => ['pdf'],
            'accept_mime' => ['application/pdf'],
        ],
        'compress_pdf' => [
            'mode' => 'backend',
            'accept_extensions' => ['pdf'],
            'accept_mime' => ['application/pdf'],
        ],
        'merge_pdf' => [
            'mode' => 'backend',
            'accept_extensions' => ['pdf'],
            'accept_mime' => ['application/pdf'],
        ],
        'split_pdf' => [
            'mode' => 'browser_first',
            'accept_extensions' => ['pdf'],
            'accept_mime' => ['application/pdf'],
        ],
        'word_to_pdf' => [
            'mode' => 'backend',
            'accept_extensions' => ['doc', 'docx', 'odt'],
            'accept_mime' => [
                'application/msword',
                'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
                'application/vnd.oasis.opendocument.text',
            ],
        ],
        'excel_to_pdf' => [
            'mode' => 'backend',
            'accept_extensions' => ['xls', 'xlsx', 'ods'],
            'accept_mime' => [
                'application/vnd.ms-excel',
                'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                'application/vnd.oasis.opendocument.spreadsheet',
            ],
        ],
        'jpg_to_pdf' => [
            'mode' => 'browser_first',
            'accept_extensions' => ['jpg', 'jpeg'],
            'accept_mime' => ['image/jpeg'],
        ],
    ],
];
